### ISSUE TITLE
苹果的可以使用硬件破解啊

### ISSUE THREAD

**Issue by sunqingquan** [yiruchujian/modifyPositioning#2]
我在网上看到一个可以使用硬件破解苹果手机定位的，我用了这个，可以用，你看和你这个有什么区别吗
[位置精灵](https://github.com/zhangxincrack/wzjl)

**Comment by chujiandaochuxia** [comment]
这个只是使用gpx文件覆盖系统的 偶尔忘记打卡用用 比较简单

**Comment by chujiandaochuxia** [comment]
业余小玩意
